name: Build

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win64]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export with Godot
        id: build
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/4.7-stable/Godot_v4.7-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.7-stable/Godot_v4.7-stable_export_templates.tpz"
          relative_project_path: "./"
          export_debug: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ steps.build.outputs.archive_directory }}
